### ISSUE TITLE
NullPointerException in CommandParsers

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/horta-hell#98]
```
[ERROR] [03/08/2014 21:49:11.782] [CodingteamSystem-akka.actor.default-dispatcher-114] [akka://CodingteamSystem/user/core] null
java.lang.NullPointerException
	at ru.org.codingteam.horta.core.CommandParsers$$anon$1.apply(CommandParsers.scala:13)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.RegexParsers$class.parse(RegexParsers.scala:148)
	at ru.org.codingteam.horta.core.SlashParsers$.parse(CommandParsers.scala:31)
	at ru.org.codingteam.horta.core.Core$$anonfun$ru$org$codingteam$horta$core$Core$$parseCommand$1.apply(Core.scala:101)
	at ru.org.codingteam.horta.core.Core$$anonfun$ru$org$codingteam$horta$core$Core$$parseCommand$1.apply(Core.scala:100)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at ru.org.codingteam.horta.core.Core.ru$org$codingteam$horta$core$Core$$parseCommand(Core.scala:100)
	at ru.org.codingteam.horta.core.Core$$anonfun$receive$1.applyOrElse(Core.scala:63)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ForNeVeR** [comment]
Somehow this shit happened again. Here's the log:

```
04:40:05.135 [CodingteamSystem-akka.actor.default-dispatcher-2847] ERROR akka.actor.OneForOneStrategy - null
java.lang.NullPointerException: null
	at ru.org.codingteam.horta.core.CommandParsers$$anon$1.apply(CommandParsers.scala:13) ~[horta-hell.jar:0.15.1]
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237) ~[horta-hell.jar:0.15.1]
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237) ~[horta-hell.jar:0.15.1]
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217) ~[horta-hell.jar:0.15.1]
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234) ~[horta-hell.jar:0.15.1]
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234) ~[horta-hell.jar:0.15.1]
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217) ~[horta-hell.jar:0.15.1]
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237) ~[horta-hell.jar:0.15.1]
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237) ~[horta-hell.jar:0.15.1]
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217) ~[horta-hell.jar:0.15.1]
	at scala.util.parsing.combinator.RegexParsers$class.parse(RegexParsers.scala:149) ~[horta-hell.jar:0.15.1]
	at ru.org.codingteam.horta.core.SlashParsers$.parse(CommandParsers.scala:31) ~[horta-hell.jar:0.15.1]
	at ru.org.codingteam.horta.core.Core$$anonfun$parseCommand$1.apply(Core.scala:151) ~[horta-hell.jar:0.15.1]
	at ru.org.codingteam.horta.core.Core$$anonfun$parseCommand$1.apply(Core.scala:150) ~[horta-hell.jar:0.15.1]
	at scala.collection.immutable.Stream.map(Stream.scala:418) ~[horta-hell.jar:0.15.1]
	at ru.org.codingteam.horta.core.Core.parseCommand(Core.scala:150) ~[horta-hell.jar:0.15.1]
	at ru.org.codingteam.horta.core.Core.ru$org$codingteam$horta$core$Core$$processMessage(Core.scala:103) ~[horta-hell.jar:0.15.1]
	at ru.org.codingteam.horta.core.Core$$anonfun$receive$1.applyOrElse(Core.scala:66) ~[horta-hell.jar:0.15.1]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[horta-hell.jar:0.15.1]
	at ru.org.codingteam.horta.core.Core.aroundReceive(Core.scala:19) ~[horta-hell.jar:0.15.1]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [horta-hell.jar:0.15.1]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [horta-hell.jar:0.15.1]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [horta-hell.jar:0.15.1]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [horta-hell.jar:0.15.1]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [horta-hell.jar:0.15.1]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [horta-hell.jar:0.15.1]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [horta-hell.jar:0.15.1]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [horta-hell.jar:0.15.1]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [horta-hell.jar:0.15.1]
```
